// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOSqNjbBEainUm57rmLTHJf18zUgU_2ws',
    appId: '1:946068071697:web:4a89789b903ecf8c5058b0',
    messagingSenderId: '946068071697',
    projectId: 'courseapp-53203',
    authDomain: 'courseapp-53203.firebaseapp.com',
    storageBucket: 'courseapp-53203.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmrVhB41SLpRujrWoYBK81wjj9Kh563c',
    appId: '1:946068071697:android:096a588fa85174775058b0',
    messagingSenderId: '946068071697',
    projectId: 'courseapp-53203',
    storageBucket: 'courseapp-53203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7FqZ8MTcApwE2rzQQgvb-rD5spIID4Y',
    appId: '1:946068071697:ios:a76580b8af2fc8ae5058b0',
    messagingSenderId: '946068071697',
    projectId: 'courseapp-53203',
    storageBucket: 'courseapp-53203.firebasestorage.app',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG7FqZ8MTcApwE2rzQQgvb-rD5spIID4Y',
    appId: '1:946068071697:ios:a76580b8af2fc8ae5058b0',
    messagingSenderId: '946068071697',
    projectId: 'courseapp-53203',
    storageBucket: 'courseapp-53203.firebasestorage.app',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOSqNjbBEainUm57rmLTHJf18zUgU_2ws',
    appId: '1:946068071697:web:c6b84732002155055058b0',
    messagingSenderId: '946068071697',
    projectId: 'courseapp-53203',
    authDomain: 'courseapp-53203.firebaseapp.com',
    storageBucket: 'courseapp-53203.firebasestorage.app',
  );

}